<script>
function selectAll(selection)
{
	select = document.getElementById(selection);
	for (i=0; i<select.length; i++) select[i].selected = true;
}

function doSubmit()
{
	selectAll('label_product_data');
	selectAll('label_country_data');
	document.forms[0].submit();
}
</script>
<?php // Zend_Debug::dump($this->errors); ?>
<form action="/label/edit/" method="post">
<fieldset>
<legend>Etikett</legend>
<input type="hidden" name = "oldNo" value="<?php echo $this->data['No']; ?>" />
<table id="label">
<tr>
	<td>Etikett</td>
	<td><?php if (isset($this->errors['label'])) : ?><div class="error"><?php endif ?>
		<?php echo $this->formText('label', $this->data['label'], array('size'=>'50')); ?>
		<?php if (isset($this->errors['label'])) : ?><br /><?php echo $this->errors['label']; ?></div><?php endif ?>
	</td>
</tr>
<tr>
	<td>Kurzform</td>
	<td><?php if (isset($this->errors['label_short'])) : ?><div class="error"><?php endif ?>
		<?php echo $this->formText('label_short', $this->data['label_short'], array('size'=>'10')); ?>
		<?php if (isset($this->errors['label_short'])) : ?><br /><?php echo $this->errors['label_short'] ?></div><?php endif ?>
	</td>
</tr>
<tr>
	<td>Produkte</td>
	<td><?php echo $this->NTMSelect('label_product', $this->labelProducts, 'product_no', 'product', $this->params['products'], 'No', 'product'); ?></td>
</tr>
<tr>
	<td>Länder</td>
	<td><?php echo $this->NTMSelect('label_country', $this->labelCountries, 'country_no', 'country', $this->params['countries'], 'Id', 'country'); ?>
	</td>
</tr>
<tr><td></td><td><button type="button" onclick="doSubmit()">Speichern</button></td></tr>
</table>
</legend>
</fieldset>
</form>


