<?php // Zend_Debug::dump($this->whm_dashboard); ?>
<div class="extrabox">
<div class="extrahead">QM</div>
<table>
<tr><th>Zertifikat</th><th>Anz</th><th>Abgel.</th><th>1 Monat</th></tr>
<?php foreach ($this->qm_dashboard as $dashboard) : ?>
<tr>
<td><?php echo $dashboard['certificate']; ?></td>
<td style="text-Align:right;"><a href="/certificate/vendorcert/"><?php echo $dashboard['certificates']; ?></a></td>
<td style="text-Align:right;"><a href="/certificate/vendorcert/end/NOW()"><?php echo $dashboard['over_due']; ?></a></td>
<td style="text-Align:right;"><a href="/certificate/vendorcert/end/NOW()%2bINTERVAL 1 MONTH"><?php echo $dashboard['over_due_m']; ?></td>
</tr>
<?php endforeach ?>
</table>
</div>
<div class="extrabox">
<div class="extrahead">Wareneingang</div>
<table>
<tr><td>Wareneingänge heute</td><td><a href="/inbound/index"><?php echo $this->ib_dashboard['inbounds_td']['cntib']; ?></a></td></tr>
</table>
</div>
<div class="extrabox">
<div class="extrahead">Lager</div>
<table>
<tr><td>Letzte Zählung:</td><td><?php echo (count($this->whm_dashboard['last_inv_comp'])>0) ? "Nr. {$this->whm_dashboard['last_inv_comp'][0]['No']} am ".date('d.m.Y', strtotime($this->whm_dashboard['last_inv_comp'][0]['ended'])) : "Keine abg. Zählung"; ?></td></tr>
<tr><td>laufende Zählung:</td><td><?php echo (count($this->whm_dashboard['act_inventory'])>0) ? "Nr. {$this->whm_dashboard['act_inventory'][0]['No']} am ".date('d.m.Y', strtotime($this->whm_dashboard['act_inventory'][0]['started'])) : "Keine akt. Zählung"; ?></td></tr>
</table>
</div>