<script>
<!--
function buildPoRow(row, orderLine)
{
	row.id = orderLine.No;
	var cellNo = row.insertCell(0);
	cellNo.className = 'data';
	cellNo.innerHTML = orderLine.vNo;
	var cellVariant = row.insertCell(1);
	cellVariant.className = 'data';
	cellVariant.innerHTML = orderLine.variant;
	var cellTradingUnits = row.insertCell(2);
	cellTradingUnits.className = 'data_num';
	cellTradingUnits.innerHTML = orderLine.tradingUnits;
	var cellPuTu = row.insertCell(3);
	cellPuTu.className = 'data_num';
	cellPuTu.innerHTML = orderLine.puTu;
	var cellPackingUnits = row.insertCell(4);
	cellPackingUnits.className = 'data_num';
	cellPackingUnits.innerHTML = orderLine.packingUnits;
	var cellPrice = row.insertCell(5);
	cellPrice.className = 'data';
	var inpPrice = document.createElement('input');
	inpPrice.name = row.id+'_price';
	inpPrice.id = row.id+'_price';
	inpPrice.value = orderLine.price;
	inpPrice.step = '0.0001';
	inpPrice.onchange = function() { editPOLine(this); };
	cellPrice.appendChild(inpPrice);
	var cellPriceAlloc = row.insertCell(6);
	cellPriceAlloc.className = 'data';
	var selPriceAlloc = document.getElementById('ini_price_alloc').cloneNode(true);
	selPriceAlloc.name = row.id+'_price_alloc';
	selPriceAlloc.id = row.id+'_price_alloc';
	selPriceAlloc.value = orderLine.priceAlloc;
	cellPriceAlloc.appendChild(selPriceAlloc);
	var cellPallets = row.insertCell(7);
	cellPallets.className = 'data_num';
	cellPallets.innerHTML = orderLine.pallets;
	var cellTuPal = row.insertCell(8);
	cellTuPal.className = 'data_num';
	cellTuPal.innerHTML = orderLine.tuPal;
	var cellTuInb = row.insertCell(9);
	cellTuInb.className = 'data_num';
	cellTuInb.innerHTML = orderLine.tuInbound;
}

function buildPoTable(orderlines)
{
	orderlineTable = document.getElementById('po_line').getElementsByTagName('tbody')[0];
	while (orderlineTable.rows.length>0) orderlineTable.deleteRow(0);
	for (cnt=0; cnt<orderlines.length; cnt++) {
		var row = orderlineTable.insertRow(cnt);
		buildPoRow(row, orderlines[cnt]);
	}
}

function getPOLines(pOrder) {

	function getPOLinesXML() {
		var row;
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {
					result = http.responseXML.getElementsByTagName('result');
					var orderlines = [];
					for (cnt=0; cnt<result.length; cnt++) {
						var orderLine = new Object();
						orderLine.No = getXMLTagValue(result[cnt], 'No') || 0;
						orderLine.purchaseOrder = getXMLTagValue(result[cnt], 'Purchase_order') || '';
						orderLine.Line = getXMLTagValue(result[cnt], 'Line') || 0;
						orderLine.vNo = getXMLTagValue(result[cnt], 'v_no') || '';
						orderLine.variant = getXMLTagValue(result[cnt], 'variant') || '';
						orderLine.tradingUnits = getXMLTagValue(result[cnt], 'Trading_Units') || 0;
						orderLine.puTu = getXMLTagValue(result[cnt], 'PU_TU') || 0;
						orderLine.packingUnits = getXMLTagValue(result[cnt], 'Packing_Units') || 0;
						orderLine.price = getXMLTagValue(result[cnt], 'Price') || 0;
						orderLine.priceAlloc = getXMLTagValue(result[cnt], 'Price_Allocation') || 0;
						orderLine.pallets = getXMLTagValue(result[cnt], 'Pallets') || 0;
						orderLine.tuPal = getXMLTagValue(result[cnt], 'TU_Pallet') || 0;
						orderLine.LineValue = getXMLTagValue(result[cnt], 'line_value') || 0;
						orderLine.tuInbound = getXMLTagValue(result[cnt], 'tu_inbound') || 0;
						orderlines.push(orderLine);
					}
					buildPoTable(orderlines);
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	createRequest();
	var URI = '/purchaseorder/getpoline/purchase_order/'+pOrder;
	sendRequest('GET', URI, '', getPOLinesXML, true);
}

function editPOLine(element)
{
	function editPOLineXML()
	{
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {					
					newNo = getXMLTagValue(http.responseXML, 'No') || '';
					price.value = getXMLTagValue(http.responseXML, 'price') || '';
					price_alloc.value = getXMLTagValue(http.responseXML, 'price_allocation') || 0;
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}

	No = element.parentNode.parentNode.id;
	price = document.getElementById(No+'_price');
	price_alloc = document.getElementById(No+'_price_alloc');
	uri = '/purchaseorder/editpoline';
	params = 'No='+No+'&price='+price.value.replace(',','.')+'&price_alloc='+price_alloc.value;
	sendRequest('POST', uri, params, editPOLineXML, true);
}
-->
</script>
<div class="data_container">
<?php echo $this->lookupSelect('ini_price_alloc', '', '', $this->params['price_allocations'], 'No', 'Allocation', array('id'=>'ini_price_alloc', 'style'=>'{width: 99%;}', 'onchange'=>'editPOLine(this)')); ?>
</div>
<a href="/purchaseorder/edit/">Neue Bestellung</a>
<hr />
<?php $pages = floor($this->params['poCount']/20) + 1; ?>
<?php $cur_page = isset($this->params['page']) ? $this->params['page'] : 1; ?>
<?php if ($pages > 1) : ?>
<div id="page">
<?php if ($cur_page>2) : ?><a href="/purchaseorder/index/page/1"><<</a>&#160;<?php endif ?>
<?php if ($cur_page>1) : ?><a href="/purchaseorder/index/page/<?php echo $cur_page-1; ?>"><</a>&#160;<?php endif ?>
<?php echo "Seite $cur_page" ?>&#160;
<?php if ($cur_page<$pages) : ?><a href="/purchaseorder/index/page/<?php echo $cur_page+1; ?>">></a>&#160;<?php endif ?>
<?php if (($cur_page+1)<$pages) : ?><a href="/purchaseorder/index/page/<?php echo $pages; ?>">>></a><?php endif ?>
</div>
<?php endif ?>
<table>
<thead>
	<tr class="data">
		<th class="data" width="20">Nummer</th>
		<th class="data" width="50">Lie.-Nr.</th>
		<th class="data" width="50">Lieferant</th>
		<th class="data" width="15">Lieferung</th>
		<th class="data" width="15">Verladung</th>
		<th class="data" width="20">LKW</th>
		<th class="data" width="20">Auflieger</th>
		<th class="data" width="20">Container</th>
		<th class="data" width="20">Incoterm</th>
	</tr>
</thead>
<tbody>	
<?php foreach($this->result as $entry) : ?>
	<tr id="<?php echo $entry['No'];?>">
		<td class="data"><input type="radio" name="po_no" value="<?php echo $entry['No']; ?>" onfocus="getPOLines(<?php echo $entry['No']; ?>)">
		<a href="/purchaseorder/edit/No/<?php echo $entry['No']; ?>"><?php echo $entry['No']; ?></a></td>
		<td class="data"><?php echo $entry['vendor_no']; ?></td>
		<td class="data"><?php echo $entry['vendor_name'].', '.$entry['vendor_city'].' '.$entry['vendor_CC']; ?></td>
		<td class="data"><?php echo $entry['arrival']; ?></td>
		<td class="data"><?php echo $entry['departure']; ?></td>
		<td class="data"><?php echo $entry['truck']; ?></td>
		<td class="data"><?php echo $entry['trailor']; ?></td>
		<td class="data"><?php echo $entry['container']; ?></td>
		<td class="data"><?php echo $entry['incoterm']; ?></td>
	</tr>
<?php endforeach ?>
</tbody>
</table>
<?php if ($pages > 1) : ?>
<div id="page">
<?php if ($cur_page>2) : ?><a href="/purchaseorder/index/page/1"><<</a>&#160;<?php endif ?>
<?php if ($cur_page>1) : ?><a href="/purchaseorder/index/page/<?php echo $cur_page-1; ?>"><</a>&#160;<?php endif ?>
<?php echo "Seite $cur_page" ?>&#160;
<?php if ($cur_page<$pages) : ?><a href="/purchaseorder/index/page/<?php echo $cur_page+1; ?>">></a>&#160;<?php endif ?>
<?php if (($cur_page+1)<$pages) : ?><a href="/purchaseorder/index/page/<?php echo $pages; ?>">>></a><?php endif ?>
</div>
<?php endif ?>
<hr />
<a href="/purchaseorder/edit/">Neue Bestellung</a>
<table id="po_line">
<thead>
<th class="data" width="20">Variante</th>
<th class="data">Beschreibung</th>
<th class="data" width="10">Kolli</>
<th class="data" width="10">Menge/Kolli</th>
<th class="data" width="12">Menge ges.</th>
<th class="data" width="10">Preis</th>
<th class="data" width="15">per</th>
<th class="data" width="6">Paletten</th>
<th class="data" width="10">Kolli / Pal.</th>
<th class="data" width="15">Kolli gel.</th>
</thead>
<tbody>
<?php foreach ($this->purchase_order_lines as $po_line) : ?>
<tr id="<?php echo $po_line['No']; ?>">
<td class="data"><?php echo $po_line['v_no']; ?></td>
<td class="data"><?php echo $po_line['variant']; ?></td>
<td class="data_num"><?php echo $po_line['Trading_Units']; ?></td>
<td class="data_num"><?php echo $po_line['PU_TU']; ?></td>
<td class="data_num"><?php echo $po_line['Packing_Units']; ?></td>
<td class="data"><input type="number" value="<?php echo $po_line['Price'];?>" name="<?php echo $po_line['No']; ?>_price" id="<?php echo $po_line['No']; ?>_price" step="0.0001" onchange="editPOLine(this)" /></td>
<td class="data"><?php echo $this->lookupSelect('price_alloc', $po_line['Price_Allocation'], 'price_allocation', $this->params['price_allocations'], 'No', 'Allocation', array('id'=>$po_line['No'].'_price_alloc', 'style'=>'{width: 99%;}', 'onchange'=>'editPOLine(this)')); ?></td>
<td class="data_num"><?php echo $po_line['Pallets']; ?></td>
<td class="data_num"><?php echo $po_line['TU_Pallet']; ?></td>
<td class="data_num"><?php echo $po_line['tu_inbound']; ?></td>
</tr>
<?php endforeach ?>
</tbody>
</table>
<hr />