<script>
notIEPopup = null;

function popupFinished()
{
	if (notIE_popup != null)  {
		notIE_popup.close();
		notIE_popup = null;
	}
}

function switchFocus(focus, direction) {
	switch (direction) {
		case 'left'		: focus = focus-1; break;
		case 'right'	: focus = focus+1; break;
		case 'down'		: focus = focus+20; break;
		case 'up'		: focus = focus-20; break;
	}
	focused = false;
	if (focus>0) {
		fields = document.getElementById('inventory_lines').getElementsByTagName('*');
		cnt = 0;
		for (cnt=0; cnt<fields.length; cnt++) {
			if (fields[cnt].hasAttribute('tabindex') && (fields[cnt].tabIndex >= focus)) {
				fields[cnt].focus();
				if (fields[cnt].select) fields[cnt].select();
				focused = true;
				break;
			}
		}
		if (!focused) switchFocus(1, 'right');
	}
}

function handleKeyDown(e, field) {
	switch (e.keyCode) {
		case 13 :	switchFocus(field.tabIndex, 'right');
					break;
//		case 37 :	switchFocus(field.tabIndex, 'left');
//					break;
//		case 38 :	switchFocus(field.tabIndex, 'up');
//					break;
//		case 39 :	switchFocus(field.tabIndex, 'right');
//					break;
//		case 40 :	switchFocus(field.tabIndex, 'down');
//					break;
	}
}



function buildRow(curRow, inventory, add)
{
	add = add || false;
	rowIndex = curRow.sectionRowIndex;
	curRow.id = inventory.No;
	var sufix = inventory.No+'_'+inventory.inventory_head+'_'+inventory.inbound_line+'_'+inventory.movement;
	var cell0 = curRow.insertCell(0);
	cell0.className = 'data';
	cell0.innerHTML = inventory.position;
//	var cell1 = curRow.insertCell(1);
//	cell1.className = 'data';
//	cell1.innerHTML = inventory.variant_desc;
//	cell1.dataset.variant = inventory.variant;
	var cell1 = curRow.insertCell(1);
	cell1.className = 'data';
	cell1.innerHTML = inventory.product_desc;
	cell1.dataset.product = inventory.product;
	var cell2 = curRow.insertCell(2);
	cell2.className = 'data';
	if (add) {
		var itemsInp = document.createElement('input');
		itemsInp.name = 'items_'+sufix;
		itemsInp.id = 'items_'+sufix;
		itemsInp.type = 'number';
		itemsInp.min = 1;
		itemsInp.max = 999;
		itemsInp.tabIndex = ((rowIndex)*40)+21;
		itemsInp.value = inventory.items;
		itemsInp.onkeydown = function() { handleKeyDown(event, this); }
		itemsInp.onclick = function() { this.select(); };
		
		var wiInp = document.createElement('input');
		wiInp.name = 'weight_item_'+sufix;
		wiInp.id = 'weight_item_'+sufix;
		wiInp.type = 'number';
		wiInp.min = 1;
		wiInp.max = 9999;
		wiInp.tabIndex = ((rowIndex)*40)+22;
		wiInp.value = inventory.weight_item;
		wiInp.onkeydown = function() { handleKeyDown(event, this); }
		wiInp.onclick = function() { this.select(); };
		cell2.appendChild(itemsInp);
		cell2.appendChild(document.createTextNode('x'));
		cell2.appendChild(wiInp);
	} else {
		cell2.innerHTML = inventory.items+'x'+inventory.weight_item+'g';
		cell2.dataset.items = inventory.items;
		cell2.dataset.weight_item = inventory.weight_item;
	}
	var cell3 = curRow.insertCell(3);
	cell3.className = 'data';
	cell3.innerHTML = inventory.origin;
	var cell4 = curRow.insertCell(4);
	cell4.className = 'data';
	if (add) {
		var t_pack_select = document.getElementById('int_t_packaging').cloneNode(true);
		t_pack_select.name = 't_packaging_'+sufix;
		t_pack_select.id = 't_packaging_'+sufix;
		t_pack_select.value = inventory.t_packaging;
		t_pack_select.tabIndex = ((rowIndex)*40)+23;
		t_pack_select.onkeydown = function() { handleKeyDown(event, this); }
		cell4.appendChild(t_pack_select);
	} else {
		cell4.innerHTML = inventory.t_packaging;
	}
	var cell5 = curRow.insertCell(5);
	cell5.className = 'data';
	if (add) {
		var packaging_select = document.getElementById('int_packaging').cloneNode(true);
		packaging_select.name = 'packaging_'+sufix;
		packaging_select.id = 'packaging_'+sufix;
		packaging_select.value = inventory.packaging;
		packaging_select.tabIndex = ((rowIndex)*40)+24;
		packaging_select.onkeydown = function() { handleKeyDown(event, this); }
		cell5.appendChild(packaging_select);
	} else {
		cell5.innerHTML = inventory.packaging_desc;
		cell5.dataset.packaging = inventory.packaging;
	}
	var cell6 = curRow.insertCell(6);
	cell6.className = 'data';
	if (add) {
		var label_select = document.getElementById('int_label').cloneNode(true);
		label_select.name = 'label_'+sufix;
		label_select.id = 'label_'+sufix;
		label_select.value = inventory.label;
		label_select.tabIndex = ((rowIndex)*40)+25;
		label_select.onkeydown = function() { handleKeyDown(event, this); }
		cell6.appendChild(label_select);
	} else {
		cell6.innerHTML = inventory.label_desc;
		cell6.dataset.label = inventory.label;
	}
	var cell7 = curRow.insertCell(7);
	cell7.className = 'data';
	if (add) {
		var lot_input = document.createElement('input');
		lot_input.type = 'text';
		lot_input.name = 'inb_lot_'+sufix;
		lot_input.id = 'inb_lot_'+sufix;
		lot_input.size = 10;
		lot_input.value = inventory.inb_lot;
		lot_input.tabIndex = ((rowIndex)*40)+26;
		lot_input.onkeydown = function() { handleKeyDown(event, this); }
		lot_input.onclick = function() { this.select(); };
		cell7.appendChild(lot_input);
	} else {
		cell7.innerHTML = inventory.inb_lot;
	}
	var cell8 = curRow.insertCell(8);
	cell8.className = 'data';
	cell8.innerHTML = inventory.arrival;
	var cell9 = curRow.insertCell(9);
	cell9.className = 'data';
	cell9.innerHTML = inventory.vendor_name;
	var cell10 = curRow.insertCell(10);
	cell10.className = 'data';
	var roomSelect = document.getElementById('filter_room').cloneNode(true);
	roomSelect.name = 'room_'+sufix;
	roomSelect.id = 'room_'+sufix;
	roomSelect.value = inventory.room;
	roomSelect.tabIndex = (add) ? ((rowIndex)*40)+27 : ((rowIndex+1)*40)+7;
	roomSelect.onchange = '';
	roomSelect.onkeydown = function() { handleKeyDown(event, this); }
	cell10.appendChild(roomSelect); 
	var cell11 = curRow.insertCell(11);
	cell11.className = 'data';
	var input_rack = document.createElement('input');
	input_rack.name = 'rack_'+sufix;
	input_rack.id = 'rack_'+sufix;
	input_rack.type = 'text';
	input_rack.size = 4;
	input_rack.value = inventory.rack;
	input_rack.tabIndex = (add) ? ((rowIndex)*40)+28 : ((rowIndex+1)*40)+8;
	input_rack.onkeydown = function() { handleKeyDown(event, this); }
	input_rack.onclick = function() { this.select(); };
	cell11.appendChild(input_rack);
	var cell12 = curRow.insertCell(12);
	cell12.className = 'data';
	input_TU_pallet = document.createElement('input');
	input_TU_pallet.name = 'tu_pallet_'+sufix;
	input_TU_pallet.id = 'tu_pallet_'+sufix;
	input_TU_pallet.type = 'number';
	input_TU_pallet.min = 0;
	input_TU_pallet.max = 999;
	input_TU_pallet.value = inventory.tu_pallet;
	input_TU_pallet.tabIndex = (add) ? ((rowIndex)*40)+29 : ((rowIndex+1)*40)+9;
	input_TU_pallet.onchange = function() { calcTU(this); };
	input_TU_pallet.onkeydown = function() { handleKeyDown(event, this); }
	input_TU_pallet.onclick = function() { this.select(); };
	cell12.appendChild(input_TU_pallet);
	var cell13 = curRow.insertCell(13);
	cell13.className = 'data';
	var input_pallets = document.createElement('input');
	input_pallets.name = 'pallets_' + sufix;
	input_pallets.id = 'pallets_' + sufix;
	input_pallets.type = 'number';
	input_pallets.min = 0;
	input_pallets.max = 99;
	input_pallets.value = inventory.pallets;
	input_pallets.tabIndex = (add) ? ((rowIndex)*40)+30 : ((rowIndex+1)*40)+10;
	input_pallets.onchange = function() { calcTU(this); };
	input_pallets.onkeydown = function() { handleKeyDown(event, this); }
	input_pallets.onclick = function() { this.select(); };
	cell13.appendChild(input_pallets);
	var cell14 = curRow.insertCell(14);
	cell14.className = 'data';
	var input_tradingUnits = document.createElement('input');
	input_tradingUnits.name = 'trading_units_' + sufix;
	input_tradingUnits.id = 'trading_units_' + sufix;
	input_tradingUnits.type = 'number';
	input_tradingUnits.min = 0;
	input_tradingUnits.max = 9999;
	input_tradingUnits.value = inventory.trading_units;
	input_tradingUnits.defaultValue = inventory.trading_units;
	input_tradingUnits.tabIndex = (add) ? ((rowIndex)*40)+31 : ((rowIndex+1)*40)+11;
	input_tradingUnits.onchange = function() { sendInventory(this); };
	input_tradingUnits.onkeydown = function() { handleKeyDown(event, this); }
	input_tradingUnits.onclick = function() { this.select(); };
	cell14.appendChild(input_tradingUnits);
	var cell15 = curRow.insertCell(15);
	cell15.className = 'data';
	var inputBlocked = document.createElement('input');
	inputBlocked.id = 'blocked_'+sufix;
	inputBlocked.name = 'blocked_'+sufix;
	inputBlocked.type = 'checkbox';
	inputBlocked.checked = (inventory.blocked==1);
	inputBlocked.tabIndex = (add) ? ((rowIndex+1)*40)+32 : ((rowIndex+1)*40)+12;
	inputBlocked.onchange = function() { sendInventory(this); };
	inputBlocked.onkeydown = function() { handleKeyDown(event, this); };
	cell15.appendChild(inputBlocked);
	var cell16 = curRow.insertCell(16);
	cell16.className = 'data';
	var qc_select = document.getElementById('qc_on_inv').cloneNode(true);
	qc_select.value = inventory.qc_on_inventory;
	qc_select.name = 'qc_on_inv_'+sufix;
	qc_select.id = 'qc_on_inv_'+sufix;
	qc_select.onchange = function() { changeInvQC(this); };
	qc_select.onkeydown = function() { handleKeyDown(event, this); };
	qc_select.tabIndex = (add) ? ((rowIndex+1)*40)+33 : ((rowIndex+1)*40)+13;
	qc_select.style.backgroundColor = (inventory.qc_on_inventory<2) ? 'rgb(0,204,0)' : ((inventory.qc_on_inventory<3) ? 'rgb(255,255,0)' : 'rgb(255,0,0)');
	cell16.appendChild(qc_select);
	var cell17 = curRow.insertCell(17);
	var linkAdd = document.createElement('a');
	linkAdd.onclick = function() { addLine(sufix) };
	linkAdd.onkeydown = function() { handleKeyDown(event, this); }
	linkAdd.innerHTML = '<img src="/images/60.ico" alt="hinzufügen" title="hinzufügen" />';
	linkAdd.tabIndex = (add) ? ((rowIndex+1)*40)+34 : ((rowIndex+1)*40)+14;
	var linkRemark = document.createElement('a');
	linkRemark.onclick = function() { editRemark(sufix); };
	linkRemark.onkeydown = function() { handleKeyDown(event, this); };
	linkRemark.innerHTML = '<img src="/images/remark16x16.png" alt="Bemerkung" title="Bemerkung" />';
	linkRemark.tabIndex = (add) ? ((rowIndex+1)*40)+35 : ((rowIndex+1)*40)+15;
	cell17.appendChild(linkAdd);
	cell17.appendChild(linkRemark);
}

function filterInventoryLines()
{
	function loadInventorylinesXML()
	{
		var row = 0;
		if (http.readyState == 4) {
			xmlResult = http.responseXML;
			var inventoryTable = document.getElementById('inventory_lines').getElementsByTagName('tbody')[0];
			invRows = inventoryTable.rows.length;
			if (xmlResult.getElementsByTagName('errorCount')[0].firstChild==null) errorCount = 0;
			else errorCount = xmlResult.getElementsByTagName('errorCount')[0].firstChild.nodeValue;
			if (errorCount==0) {
				inventories = xmlResult.getElementsByTagName('result');
				for (var inv = 0; inv < inventories.length; inv++) {
					var inventory = [];
					if (row >= invRows) {
						var currentRow = inventoryTable.insertRow(row);
					} else {
						var currentRow = inventoryTable.rows[row];
						while (currentRow.cells.length>0) 
							currentRow.deleteCell(0);
					}
					if (!inventories[inv].getElementsByTagName('No')[0].firstChild) 
						inventory['No']  = 0;
					else
						inventory['No'] = inventories[inv].getElementsByTagName('No')[0].firstChild.nodeValue;
					if (!inventories[inv].getElementsByTagName('inventory_head')[0].firstChild)
						inventory['inventory_head'] = 0;
					else 
						inventory['inventory_head'] = inventories[inv].getElementsByTagName('inventory_head')[0].firstChild.nodeValue;
					if (!inventories[inv].getElementsByTagName('inbound_line')[0].firstChild)
						inventory['inbound_line'] = 0;
					else
						inventory['inbound_line'] = inventories[inv].getElementsByTagName('inbound_line')[0].firstChild.nodeValue;
					inventory['movement'] = getXMLTagValue(inventories[inv], 'movement') || 0;
					inventory['position'] = inventories[inv].getElementsByTagName('position')[0].firstChild.nodeValue;
					inventory['variant'] = inventories[inv].getElementsByTagName('variant')[0].firstChild.nodeValue;
					inventory['variant_desc'] = inventories[inv].getElementsByTagName('variant_desc')[0].firstChild.nodeValue;
					inventory['product'] = inventories[inv].getElementsByTagName('product')[0].firstChild.nodeValue;
					inventory['product_desc'] = inventories[inv].getElementsByTagName('product_desc')[0].firstChild.nodeValue;
					inventory['origin'] = inventories[inv].getElementsByTagName('origin')[0].firstChild.nodeValue;
					inventory['items'] = getXMLTagValue(inventories[inv], 'items') || 0;
					inventory['weight_item'] = getXMLTagValue(inventories[inv], 'weight_item') || 0;
					inventory['t_packaging'] = inventories[inv].getElementsByTagName('t_packaging')[0].firstChild.nodeValue;
					inventory['packaging_desc'] = inventories[inv].getElementsByTagName('packaging')[0].firstChild.nodeValue;
					inventory['packaging'] = inventories[inv].getElementsByTagName('packaging_no')[0].firstChild.nodeValue;
					inventory['label_desc'] = inventories[inv].getElementsByTagName('label')[0].firstChild.nodeValue;
					inventory['label'] = inventories[inv].getElementsByTagName('label_no')[0].firstChild.nodeValue;
					if (!inventories[inv].getElementsByTagName('inb_lot')[0].firstChild)
						inventory['inb_lot'] = '';
					else inventory['inb_lot'] = inventories[inv].getElementsByTagName('inb_lot')[0].firstChild.nodeValue;
					arrival = inventories[inv].getElementsByTagName('inb_arrival')[0].firstChild.nodeValue.split(" ")[0].split("-");
					inventory['arrival'] = arrival[2]+'.'+arrival[1]+'.'+arrival[0];
					inventory['vendor_name'] = getXMLTagValue(inventories[inv], 'vendor_name') || '';
					inventory['stock'] = inventories[inv].getElementsByTagName('stock')[0].firstChild.nodeValue;
					inventory['room'] = inventories[inv].getElementsByTagName('room')[0].firstChild.nodeValue;
					inventory['rack'] = inventories[inv].getElementsByTagName('rack')[0].firstChild.nodeValue;
					inventory['tu_pallet'] = inventories[inv].getElementsByTagName('tu_pallet')[0].firstChild.nodeValue;
					inventory['pallets'] = inventories[inv].getElementsByTagName('pallets')[0].firstChild.nodeValue;
					inventory['trading_units'] = inventories[inv].getElementsByTagName('trading_units')[0].firstChild.nodeValue;
					inventory['blocked'] = getXMLTagValue(inventories[inv], 'blocked') || 0;
					inventory['qc_on_inventory'] = getXMLTagValue(inventories[inv], 'qc_on_inventory') || 1;
					buildRow(currentRow, inventory);
					row++;
				}
			} if (invRows>row) {
				var lastRow=row;
				do {
					inventoryTable.deleteRow(lastRow);
					row++;
				} while (row<invRows)
			}
		}	
	}
	
	var filter_position = document.getElementById('filter_position').value;
	var filter_product = document.getElementById('filter_product').value;
	var filter_room = document.getElementById('filter_room').value;
	params = '/inventory_head/'+document.getElementById('head_no').innerHTML;
	if (filter_position!='') params += '/position/'+filter_position;
	if (filter_product!='') params += '/product/'+filter_product;
	uri = '/whmanagement/getlines'+params;
	sendRequest('GET', uri, '', loadInventorylinesXML, false);
}

function calcTU(element)
{
	var name = element.name;
	var items = name.split('_');
	var sufix = items[1]+'_'+items[2]+'_'+items[3]+'_'+items[4];
	var TU_pallet = document.getElementById('tu_pallet_'+sufix).value;
	var pallets = document.getElementById('pallets_'+sufix).value;
	document.getElementById('trading_units_'+sufix).value = TU_pallet*pallets;
	sendInventory(element);
}

function sendInventory(element, overwrite)
{
	var room;
	var rack;
	var TU_pallet;
	var pallets;
	var trading_units;
	var newItem = false;
	
	function getInventoryReturn()
	{
		if (http.readyState == 4) {
			if (http.status != 200) {
				alert('Serverfehler '+http.status+'!');
			}
			if (http.responseXML) {
				xmlResult = http.responseXML;
				if (xmlResult.getElementsByTagName('errorCount')[0].firstChild == null) var errorCount = 0;
				else var errorCount = xmlResult.getElementsByTagName('errorCount')[0].firstChild.nodeValue;
				if (errorCount == 0) {
					trading_units.defaultValue = xmlResult.getElementsByTagName('trading_units')[0].firstChild.nodeValue;
					trading_units.value = xmlResult.getElementsByTagName('trading_units')[0].firstChild.nodeValue;
					room.value = xmlResult.getElementsByTagName('room')[0].firstChild.nodeValue;
					rack.value = xmlResult.getElementsByTagName('rack')[0].firstChild.nodeValue;
					pallets.value = xmlResult.getElementsByTagName('pallets')[0].firstChild.nodeValue;
					TU_pallet.value = xmlResult.getElementsByTagName('tu_pallet')[0].firstChild.nodeValue;
					if (newItem) {
						No = xmlResult.getElementsByTagName('No')[0].firstChild.nodeValue;
						inventory_head = xmlResult.getElementsByTagName('inventory_head')[0].firstChild.nodeValue;
						inbound_line = xmlResult.getElementsByTagName('inbound_line')[0].firstChild.nodeValue;
						movement = xmlResult.getElementsByTagName('movement')[0].firstChild.nodeValue;
						newSufix = No+'_'+inventory_head+'_'+inbound_line+'_'+movement;
						room.name = 'room_'+newSufix;
						room.id = 'room_'+newSufix;
						rack.name = 'rack_'+newSufix;
						rack.id = 'rack_'+newSufix;
						pallets.name = 'pallets_'+newSufix;
						pallets.id = 'pallets_'+newSufix;
						TU_pallet.name = 'tu_pallet_'+newSufix;
						TU_pallet.id = 'tu_pallet_'+newSufix;
						trading_units.name = 'trading_units_'+newSufix;
						trading_units.id = 'trading_units_'+newSufix;
						blocked.id = 'blocked_'+newSufix;
						blocked.name = 'blocked_'+newSufix;
						qcOnInv.id = 'qc_on_inv_'+newSufix;
						qcOnInv.name = 'qc_on_inv_'+newSufix;
					//	filterInventoryLines();
					//	setTimeout(document.getElementById('trading_units_'+newSufix).focus(), 2000);
					//	trading_units.select();
					}
				} else {
					errorText = '';
					if (xmlResult.getElementsByTagName('race_condition').length>0) {
						race_condition = xmlResult.getElementsByTagName('race_condition')[0].firstChild.nodeValue;
						if (confirm('Der Wert wurde bereits von einem anderen benutzer auf '+race_condition+' geändert. Möchten Sie den Wert übernehmen?\nOK=anderen Wert übernehmen  Abbrechen=Eigenen Wert nehmen.')==false) {
							sendInventory(element, true);
						} else {
							trading_units.defaultValue = race_condition;
							trading_units.value = race_condition;
							room.value = xmlResult.getElementsByTagName('room')[0].firstChild.nodeValue;
							rack.value = xmlResult.getElementsByTagName('rack')[0].firstChild.nodeValue;
							pallets.value = xmlResult.getElementsByTagName('pallets')[0].firstChild.nodeValue;
							TU_pallet.value = xmlResult.getElementsByTagName('tu_pallet')[0].firstChild.nodeValue;
						}	
					} else {
						var errorText = '';
						var errors = xmlResult.getElementsByTagName('error');
						for (e=0; e<errors.length; e++) {
							errorText += errors[e].getElementsByTagName('error_field')[0].firstChild.nodeValue + ': ';
							errorText += errors[e].getElementsByTagName('error_text')[0].firstChild.nodeValue + '\n';
						}
						alert(errorText);
					}
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	
	overwrite = overwrite || false; 
	var name = element.name;
	var items = name.split('_');
	newItem = (items[items.length-4]=='0');
	var sufix = items[items.length-4]+'_'+items[items.length-3]+'_'+items[items.length-2]+'_'+items[items.length-1];
	TU_pallet = document.getElementById('tu_pallet_'+sufix);
	pallets = document.getElementById('pallets_'+sufix);
	trading_units = document.getElementById('trading_units_'+sufix);
	room = document.getElementById('room_'+sufix);
	rack = document.getElementById('rack_'+sufix);
	var no = items[items.length-4];
	var inventory_head = items[items.length-3];
	var inbound_line = items[items.length-2];
	var movement = items[items.length-1];
	var blocked = document.getElementById('blocked_'+sufix);
	var qcOnInv = document.getElementById('qc_on_inv_'+sufix);
	var postData = 'No='+no;
	postData += '&inventory_head='+inventory_head;
	postData += '&inbound_line='+inbound_line;
	postData += '&movement='+movement;
	postData += '&room='+room.value;
	postData += '&rack='+rack.value;
	postData += '&tu_pallet='+TU_pallet.value;
	postData += '&pallets='+pallets.value;
	postData += '&trading_units='+trading_units.value;
	postData += '&default_TU='+trading_units.defaultValue;
	postData += '&blocked=';
	postData += (blocked.checked) ? '1' : '0';
	postData += '&qc_on_inventory='+qcOnInv.value;
	if (document.getElementById('items_'+sufix)) postData += '&items='+document.getElementById('items_'+sufix).value;
	if (document.getElementById('weight_item_'+sufix)) postData += '&weight_item='+document.getElementById('weight_item_'+sufix).value;
	if (document.getElementById('t_packaging_'+sufix)) postData += '&t_packaging='+document.getElementById('t_packaging_'+sufix).value;
	if (document.getElementById('packaging_'+sufix)) postData += '&packaging='+document.getElementById('packaging_'+sufix).value;
	if (document.getElementById('label_'+sufix)) postData += '&label='+document.getElementById('label_'+sufix).value;
	if (document.getElementById('inb_lot_'+sufix)) postData += '&inb_lot='+document.getElementById('inb_lot_'+sufix).value;
	postData += '&overwrite='+overwrite;
	sendRequest('POST', '/whmanagement/storeinventory/', postData, getInventoryReturn, false);
}

function addLine(sufix)
{
	
	var items = sufix.split('_');
	var inventoryTable = document.getElementById('inventory_lines').getElementsByTagName('tbody')[0];
	invRows = inventoryTable.rows.length;
	curRow = inventoryTable.rows.namedItem(items[0]);
	var inventory = [];
	inventory['No'] = '0';
	inventory['inventory_head'] = items[1];
	inventory['inbound_line'] = items[2];
	inventory['movement'] = items[3];
	inventory['position'] = curRow.cells[0].innerHTML;
//	inventory['variant_desc'] = curRow.cells[1].innerHTML;
//	inventory['variant'] = curRow.cells[1].dataset.variant;
	inventory['product_desc'] = curRow.cells[1].innerHTML;
	inventory['product'] = curRow.cells[1].dataset.product;
	inventory['origin'] = curRow.cells[3].innerHTML;
	inventory['items'] = curRow.cells[2].dataset.items;
	inventory['weight_item'] = curRow.cells[2].dataset.weight_item;
	inventory['t_packaging'] = curRow.cells[4].innerHTML;
	inventory['packaging_desc'] = curRow.cells[5].innerHTML;
	inventory['packaging'] = curRow.cells[5].dataset.packaging;
	inventory['label_desc'] = curRow.cells[6].innerHTML;
	inventory['label'] = curRow.cells[6].dataset.label;
	inventory['inb_lot'] = curRow.cells[7].innerHTML;
	inventory['arrival'] = curRow.cells[8].innerHTML;
	inventory['vendor_name'] = curRow.cells[9].innerHTML;
//	inventory['stock'] = curRow.cells[9].innerHTML;
	inventory['room'] = document.getElementById('room_'+sufix).value;
	inventory['rack'] = document.getElementById('rack_'+sufix).value;
	inventory['tu_pallet'] = document.getElementById('tu_pallet_'+sufix).value;
	inventory['pallets'] = 0;
	inventory['trading_units'] = 0;
	inventory['blocked'] = 0;
	inventory['qc_on_inventory'] = 1;
	newSufix = inventory['No']+'_'+inventory['inventory_head']+'_'+inventory['inbound_line']+'_'+inventory['movement'];
	newRow = inventoryTable.insertRow(curRow.sectionRowIndex+1);
	buildRow(newRow, inventory, true);
	document.getElementById('pallets_'+newSufix).focus();
	document.getElementById('pallets_'+newSufix).select();
}

function closeInventory()
{
	if (confirm('Die Zählung wird beendet und es können keine weiteren Werte erfaßt werden!'))
		location.href='/whmanagement/closeinventory/No/<?php echo $this->params['inventory_head']['No']; ?>';
}

function editRemark(sufix)
{
	var items = sufix.split('_');
	
	URI = '/inbound/editremarkdialog/No/'+items[2];
	notIE_popup = window.open(URI, 'Bemerkungen', 'dialogWidth=600px;dialogHeight=400px;diologLeft=0;dialogTop=100;resizable=yes;scroll=yes');
}

function changeInvQC(select)
{
	i=0;
	while (select.options[i]) {
		if (select.options[i].selected==true) select.style.backgroundColor = select.options[i].style.backgroundColor;
		i++;
	}
	sendInventory(select);
}

</script>
<?php $rooms = $this->params['rooms']; ?>
<?php $products = $this->params['products']; ?>
<?php $t_packagings = $this->params['t_packagings']; ?>
<?php $packagings = $this->params['packagings']; ?>
<?php $labels = $this->params['labels']; ?>
<?php $qualities = $this->params['qualities']; ?>
<?php $inventory_head = $this->params['inventory_head']; ?>
<?php $inventory_lines = $this->params['inventory_lines']; ?>
<?php $errors = $this->params['errors']; ?>
<?php $filter = array('product'=>'', 'room'=>''); ?>
<?php if (isset($errors['all'])) : ?>
<div class="error"><?php echo $errors['all']; ?></div>
<?php endif ?>
<?php if (isset($inventory_head['No'])) : ?>
<h3>Zählung <span id="head_no"><?php echo $inventory_head['No']; ?></span> vom <span id="head_date"><?php echo $inventory_head['date']; ?></span></h3>
<button id="inventory_close" onclick="closeInventory()">Zählung beenden</button>
<?php endif ?>
<div class="data_container">
<select name="int_t_packaging" id="int_t_packaging">
<?php foreach ($t_packagings as $t_packaging) : ?>
<option value="<?php echo $t_packaging['no']; ?>"><?php echo $t_packaging['transport_packaging']; ?></option>
<?php endforeach ?>
</select>
<select name="int_packaging" id="int_packaging">
<?php foreach ($packagings as $packaging) : ?>
<option value="<?php echo $packaging['No']; ?>"><?php echo $packaging['packaging']; ?></option>
<?php endforeach ?>
</select>
<select name="int_label" id="int_label">
<?php foreach ($labels as $label) : ?>
<option value="<?php echo $label['No']; ?>"><?php echo $label['label']; ?></option>
<?php endforeach ?>
</select>
<select name="qc_on_inv" id="qc_on_inv" onchange="changeInvQC(this)">
<option value="1" style="background-color: rgb(0,204,0)">1</option>
<option value="2" style="background-color: rgb(255,255,0)">2</option>
<option value="3" style="background-color: rgb(255,0,0)">3</option>
</select>
</div>

<div class="filter">
<table id="filter">
<tr>
	<td>Position</td>
	<td>Produkt</td>
	<td>Raum</td>
</tr>
<tr>
	<td><input type="text" id="filter_position" name="filter_position" accesskey="O" tabindex="1" value="" size="10" onchange="filterInventoryLines()" onkeydown="handleKeyDown(event, this)" /></td>
	<td><select id="filter_product" name="filter_product" accesskey="p" tabindex="2" onchange="filterInventoryLines()">
	<?php foreach ($products as $product) : ?>
	<option value="<?php echo $product['No']; ?>"<?php if ($product['No']==$filter['product']) echo " selected"; ?>><?php echo $product['product']; ?></option>
	<?php endforeach ?>
	</select></td>
	<td><select id="filter_room" name="filter_room" accesskey="r" tabindex="3" onchange="filterInventoryLines()">
	<?php foreach ($rooms as $room) : ?>
	<option value="<?php echo $room['No']; ?>"<?php if ($room['No']==$filter['room']) echo " selected"; ?>><?php echo $room['room']; ?></option>
	<?php endforeach ?>
	</select></td>
</tr>
</table>
</div>
<table id="inventory_lines">
<thead>
<tr>
	<th class="data">Position</th>
	<th class="data">Artikel</th>
	<th class="data">Einheit</th>
	<th class="data">Herkunft</th>
	<th class="data">Transp. V</th>
	<th class="data">Verpackung</th>
	<th class="data">Etikett</th>
	<th class="data">Los</th>
	<th class="data">Datum</th>
	<th class="data">Lieferant</th>
	<th class="data">Raum</th>
	<th class="data">Regal</th>
	<th class="data">Kol/Pal</th>
	<th class="data">Pal.</th>
	<th class="data">Kolli</th>
	<th class="data"><img src="/images/s_cancel.png" /></th>
	<th class="data">QC</th>
	<th></th>
</tr>
</thead>
<tbody>
<?php $row = 0; ?>
<?php foreach ($inventory_lines as $inventory_line) : ?>
<?php if ($inventory_line['No'] == '') $inventory_line['No'] = 0; ?>
<?php $sufix = $inventory_line['No'].'_'.$inventory_head['No'].'_'.$inventory_line['inbound_line'].'_'.$inventory_line['movement']; ?>
<tr id="<?php echo $inventory_line['No']; ?>">
	<td class="data"><?php echo $inventory_line['position']; ?></td>
	<td class="data" data-product="<?php echo $inventory_line['product']; ?>"><?php echo $inventory_line['product_desc']; ?></td>
	<td class="data" data-items="<?php echo $inventory_line['items']; ?>" data-weight_item="<?php echo $inventory_line['weight_item']; ?>"><?php echo "{$inventory_line['items']}x{$inventory_line['weight_item']}g"; ?></td>
	<td class="data"><?php echo $inventory_line['origin']; ?></td>
	<td class="data"><?php echo $inventory_line['t_packaging']; ?></td>
	<td class="data" data-packaging="<?php echo $inventory_line['packaging_no']; ?>"><?php echo $inventory_line['packaging']; ?></td>
	<td class="data" data-label="<?php echo $inventory_line['label_no']; ?>"><?php echo $inventory_line['label']; ?></td>
	<td class="data"><?php echo $inventory_line['inb_lot']; ?></td>
	<td class="data"><?php echo date('d.m.Y',strtotime($inventory_line['inb_arrival'])); ?></td>
	<td class="data"><?php echo $inventory_line['vendor_name']; ?></td>
	<td class="data"><select id="room_<?php echo $sufix; ?>" name="room_<?php echo $sufix; ?>" tabindex="<?php echo (($row+1)*40)+7; ?>" onkeydown="handleKeyDown(event, this)">
					<?php foreach ($rooms as $room) : ?>
					<option value="<?php echo $room['No']; ?>"<?php if ($room['No']==$inventory_line['room']) echo " selected";?>><?php echo $room['room']; ?></option>
					<?php endforeach ?>
					</select>
	</td>
	<td class="data"><input type="text" id="rack_<?php echo $sufix; ?>" name="rack_<?php echo $sufix; ?>" value="<?php echo $inventory_line['rack']; ?>" size="4" tabindex="<?php echo (($row+1)*40)+8; ?>" onclick="this.select()" onkeydown="handleKeyDown(event, this)" />
	<td class="data"><input type="number" id="tu_pallet_<?php echo $sufix; ?>" name="tu_pallet_<?php echo $sufix; ?>" value="<?php echo $inventory_line['tu_pallet']; ?>" min="0" max="999" tabindex="<?php echo (($row+1)*40)+9; ?>" onchange="calcTU(this)" onclick="this.select()" onkeydown="handleKeyDown(event, this)" />
	<td class="data"><input type="number" id="pallets_<?php echo $sufix; ?>" name="pallets_<?php echo $sufix; ?>" value="<?php echo $inventory_line['pallets']; ?>" min="0" max="99" tabindex="<?php echo (($row+1)*40)+10; ?>" onclick="this.select()" onchange="calcTU(this)" onkeydown="handleKeyDown(event, this)" />
	<td class="data"><input type="number" id="trading_units_<?php echo $sufix; ?>" name="trading_units_<?php echo $sufix; ?>" value="<?php echo $inventory_line['trading_units']; ?>" defaultValue="<?php echo $inventory_line['trading_units']; ?>" min="0" max="9999" tabindex="<?php echo (($row+1)*40)+11; ?>" onclick="this.select()" onchange="sendInventory(this)"  onkeydown="handleKeyDown(event, this)" />
	<td class="data"><input type="checkbox" tabindex="<?php echo (($row+1)*40)+12; ?>" id="blocked_<?php echo $sufix; ?>" name="blocked_<?php echo $sufix; ?>"<?php if ($inventory_line['blocked']==1) echo ' checked="checked"'; ?> onkeydown="handleKeyDown(event, this)" onchange="sendInventory(this)" /></td>
	<td class="data">
		<select tabindex="<?php echo (($row+1)*40)+13; ?>" name="qc_on_inv_<?php echo $sufix; ?>" id="qc_on_inv_<?php echo $sufix; ?>" onchange="changeInvQC(this)" onkeydown="handleKeyDown(event, this)" style="background-color: <?php echo ($inventory_line['qc_on_inventory']<2) ? 'rgb(0,204,0)' : (($inventory_line['qc_on_inventory']<3) ? 'rgb(255,255,0' : 'rgb(255,0,0)'); ?>">
		<option value="1"<?php if(round($inventory_line['qc_on_inventory'])<2) echo " selected"; ?> style="background-color: rgb(0,204,0)">1</option>
		<option value="2"<?php if (round($inventory_line['qc_on_inventory'])>=2 && round($inventory_line['qc_on_inventory'])<3) echo " selected"; ?> style="background-color: rgb(255,255,0)">2</option>
		<option value="3"<?php if(round($inventory_line['qc_on_inventory'])>=3) echo " selected"; ?> style="background-color: rgb(255,0,0)">3</option>
		</select></td>
	<td><a tabindex="<?php echo (($row+1)*40)+14; ?>" onkeydown="handleKeyDown(event, this)" onclick="addLine('<?php echo $sufix; ?>')"><img src="/images/60.ico" alt="hinzufügen" title="hinzufügen" /></a>
		<a tabindex="<?php echo (($row+1)*40)+15; ?>" onkeydown="handleKeyDown(event, this)" onclick="editRemark('<?php echo $sufix; ?>')"><img src="/images/remark16x16.png" alt="Bemerkung" title="Bemerkung" /></a></td>
</tr>
<?php $row++; ?>
<?php endforeach ?>
</tbody>
</table>