<script>
function openLanguageDialog(element)
{
	id = element.parentNode.parentNode.id;
	URI = '/language/languagedialog/table/quality_checkpoint/column/quality_checkpoint/key/'+id;
	dimensions = 'width=500,height=400,left='+event.screenX+',top='+event.screenY+',resizable=yes,scroll=yes';
	window.open(URI, 'Sprachversionen', dimensions);
}
</script>
<table id="quality_checkpoints">
<thead>
<tr>
	<th class="data">Nummer</th>
	<th class="data">Prüfpunkt</th>
	<th class="data">Art</th>
	<th class="data">Klasse</th>
	<th class="data">Max. sehrgut</td>
	<th class="data">Max. gut</th>
	<th class="data">Max. Befr.</th>
	<th class="data">max. ausr.</th>
	<th class="data">max. mangelh.</th>
	<th class="data">Operator</th>
</tr>
</thead>
<tbody>
<?php foreach($this->data as $data) : ?>
<tr id="<?php echo $data['No']; ?>">
	<td class="data"><a href="/qcheckpoint/editgeneral/No/<?php echo $data['No']; ?>"><?php echo $data['No']; ?></a></td>
	<td class="data"><?php echo $data['quality_checkpoint']; ?><a onclick="openLanguageDialog(this)"><img src="/images/b_more.png" alt="Sprachen" title="Sprachen" /></a></td>
	<td class="data"><?php echo $data['qc_type']; ?></td>
	<td class="data"><?php echo $data['qcheckpoint_class']; ?></td>
	<td class="data"><?php echo $data['max_verygood']; ?></td>
	<td class="data"><?php echo $data['max_good']; ?></td>
	<td class="data"><?php echo $data['max_ok']; ?></td>
	<td class="data"><?php echo $data['max_regular']; ?></td>
	<td class="data"><?php echo $data['max_almostregular']; ?></td>
	<td class="data"><?php echo $data['operator_name']; ?></td>
</tr>
<?php endforeach ?>
</tbody>
</table>
<a href="/qcheckpoint/editgeneral/">Neuer Kontrollpunkt</a>