<script>
function openLanguageDialog(element)
{
	id = element.parentNode.parentNode.id;
	URI = '/language/languagedialog/table/product/column/product/key/'+id;
	dimensions = 'width=500,height=400,left='+event.screenX+',top='+event.screenY+',resizable=yes,scroll=yes';
	window.open(URI, 'Sprachversionen', dimensions);
}
</script>
<hr />
<table class="data">
	<tr class="data">
		<th class="data">Nummer</th>
		<th class="data">Produkt</th>
		<th class="data">Gruppe</th>
	</tr>
<?php foreach($this->products as $entry) :  ?>
	<tr id="<?php echo $entry['No']; ?>">
		<td class="data"><a href="/product/edit/id/<?php echo $entry['No']; ?>"><?php echo $entry['No']; ?></td>
		<td class="data"><?php echo $entry['product']; ?><a onclick="openLanguageDialog(this)" ><img src="/images/b_more.png" alt="Sprachen" title="Sprachen" /></a></td>
		<td class="data"><?php echo $entry['product_group']; ?></td>
	</tr>
<?php endforeach; ?>
</table>
<a href="/product/edit/">Neues Produkt</a>
<hr />