<script>
var lastPO_Line;

function fillVendortable(vendor)
{
	var vendorTable = document.getElementById('vendor_table').getElementsByTagName('tbody')[0];
	var rowCnt = vendorTable.rows.length;
	var rowNr = 0;
	for (vc=0; vc<vendor.length; vc++) {
		if ((vc) >= rowCnt) {
			row=vendorTable.insertRow(vc);
			var tdNo=row.insertCell(0);
			var tdName=row.insertCell(1);
			var tdStreet=row.insertCell(2);
			var tdCity=row.insertCell(3);
		} else {
			row=vendorTable.rows[vc];
			var tdNo=row.cells(0);
			var tdName=row.cells(1);
			var tdStreet=row.cells(2);
			var tdCity=row.cells(3);
		}
		tdNo.innerHTML='<input type="radio" name="v_no" value="'+vendor[vc].getElementsByTagName('No')[0].firstChild.nodeValue+'">'+vendor[vc].getElementsByTagName('No')[0].firstChild.nodeValue;
		tdNo.className="data";
		tdName.innerHTML=vendor[vc].getElementsByTagName('name')[0].firstChild.nodeValue;
		tdName.className="data";
		tdStreet.innerHTML=vendor[vc].getElementsByTagName('street')[0].firstChild.nodeValue;
		tdStreet.className="data";
		tdCity.innerHTML=vendor[vc].getElementsByTagName('city')[0].firstChild.nodeValue;
		tdCity.className="data";
		if (rowCnt>vc) {
			var lastRow=vc;
			do {
				vendorTable.deleteRow(lastRow);
				vc++;
			} while (vc<rowCnt)
		}
	}
}

function newVariantRow(row, line);
{
	var tdVariant=row.insertCell(0);
	var inpVariant = document.createElement('input');
	inpVariant.type = 'text';
	inpVariant.name = 'v_no';
	inpVariant.id = 'v_no_'+line;
	inpVariant.size = 30;
	inpVariant.maxlength = 30;
	tdVariant.appendChild(inpVariant);
	
	var tdarticle=row.insertCell(1);
	var inpProduct = new document.createElement('input');
	inpProduct.type = 'text';
	inpProduct.name = 'variant';
	inpProduct.size = 50;
	inpProduct.maxlength = 255;
	tdarticle.appendChild(inpProduct);
	
	var tdTU=row.insertCell(2);
	var inpTU = new document.createElement('input');
	inpTU.name = 'Trading_Units';
	inpTU.type = 'number';
	inpTU.size = 8;
	impTU.min = 0;
	tdTU.appendChild(inpTU);
	
	var tdPU_TU=row.insertCell(3);
	var inpPU_TU = new document.createElement('input');
	inpPU_TU.type = 'number';
	inpPU_TU.name = 'PU_TU';
	inpPU_TU.size = 8;
	impPU_TU.min = 0;
	tdPU_TU.appendChild(inpPU_TU);

	var tdPU=row.insertCell(4);
	var inpPU = new document.createElement('input');
	inpPU.type = 'number';
	inpPU.name = 'Packing_Units';
	inpPU.size = 8;
	impPU.min = 0;
	tdPU.appendChild(inpPU);
	
	var tdPallets=row.insertCell(5);
	var inpPallets = new document.createElement('input');
	inpPallets.type = 'number';
	inpPallets.name = 'Pallets';
	inpPallets.size = 8;
	impPallets.min = 0;
	tdPallets.appendChild(inpPallets);
	
	var tdTU_Pal=row.insertCell(6);
	var inpTU_Pal = new document.createElement('input');
	inpTU_Pal.type = 'number';
	inpTU_Pal.name = 'TU_Pallets';
	inpTU_Pal.size = 8;
	impTU_Pal.min = 0;
	tdTU_Pal.appendChild(inpTU_Pal);
}

function fillPO_LineTable(PO_Line)
{
	var POLineTable = document.getElementById('PO_Lines').getElementsByTagName('tbody')[0];
	var rowCnt = PO_LineTable.rows.length;
	var rowNr = 0;
	for (vc=0; vc<PO_Line.length; vc++) {
		if ((vc) >= rowCnt) {
			newVariantRow(po_lineTable.insertRow(vc));
		}
		row=po_lineTable.rows[vc];
		var inpVariants = row.cells(0).getElementsByTagName('v_no')[0];
		var inpArticle=row.cells(1).getElementsByTagName('variant')[0];
		var inpTU=row.cells(2).getElementsByTagName('Trading_Units')[0];
		var inpPU_TU=row.cells(3).getElementsByTagName('PU_TU')[0];
		var tdPU=row.cells(4).getElementsByTagName('Packing_Units')[0];
		var tdPallets=row.cells(5).getElementsByTagName('Pallets')[0];
		var tdTU_Pal=row.cells(6).getElementsByTagName('TU_Pallet')[0];
		tdVariant.innerHTML=po_lines[vc].getElementsByTagName('v_no')[0].firstChild.nodeValue;
		tdVariant.className="data";
		tdarticle.innerHTML=po_lines[vc].getElementsByTagName('variant')[0].firstChild.nodeValue;
		tdarticle.className="data";
		tdTU.innerHTML=po_lines[vc].getElementsByTagName('Trading_Units')[0].firstChild.nodeValue;
		tdTU.className="data_num";
		tdPU_TU.innerHTML=po_lines[vc].getElementsByTagName('PU_TU')[0].firstChild.nodeValue;
		tdPU_TU.className="data_num";
		tdPU.innerHTML=po_lines[vc].getElementsByTagName('Packing_Units')[0].firstChild.nodeValue;
		tdPU.className="data_num";
		tdPallets.innerHTML=po_lines[vc].getElementsByTagName('Pallets')[0].firstChild.nodeValue;
		tdPallets.className="data_num";
		tdTU_Pal.innerHTML=po_lines[vc].getElementsByTagName('TU_Pallet')[0].firstChild.nodeValue;
		tdTU_Pal.className="data_num";
	}
	if (rowCnt>vc) {
		var lastRow=vc;
		do {
			vendorTable.deleteRow(lastRow);
			vc++;
		} while (vc<rowCnt)
	}
	lastPO_Line = po_lines[vc].getElementsByTagName('line')[0].firstChild.nodeValue;
}


function loadVendor()
{
	function loadVendorXML()
	{
		if (http.readyState==4) {
			xmlResult = http.responseXML;
			if (xmlResult.getElementsByTagName('errorCount')[0].firstChild==null) errorCount = 0;
			else errorCount = xmlResult.getElementsByTagName('errorCount')[0].firstChild.nodeValue;
			if (errorCount==0) {
				var vendor = xmlResult.getElementsByTagName('result');
				if (vendor.length==1) {
					var vendor_name = vendor[0].getElementsByTagName('name')[0].firstChild.nodeValue;
					vendor_name = vendor_name + ", "+vendor[0].getElementsByTagName('city')[0].firstChild.nodeValue;
					document.getElementById('vendor_name').innerHTML=vendor_name;
				} else {
					var dialog = document.getElementById('vendor_dialog');
					filltable(vendor);
//					dialog.showModal();
					URI = '/vendor/vendordialog/No/'+document.getElementById('vendor_no').value;
					result=window.showModalDialog(URI,null,
		                       'dialogWidth=600px;dialogHeight=400px;diologLeft=0;dialogTop=100;resizable=yes;scroll=yes');
					document.getElementById('vendor_no').value = result['no'];
					document.getElementById('vendor_address').innerHTML = result['name']+"<br />"+result['street']+"<br />"+result['city']+"<br />"+result['country_code'];
				}
			} else {
				var errors = xmlResult.getElementsByTagName('error');
				for (e = 0; e < errorCount; e++) {
					field = errors[e].childNodes[1].nodeName;
					value = errors[e].childNodes[1].firstChild.nodeValue;
					var errorText = errorText+"["+field+"] "+value+"\n";
				}
				alert(errorText);
			}
		}
	}
	
	createRequest();
	var URI = '/vendor/get/No/'+document.getElementById('vendor_no').value;
	sendRequest("GET", URI, '', loadVendorXML, true);
}

function loadVariant(line)
	
	function loadVariantXML()
	{
		if (http.readyState==4) {
			var variant = [];
			xmlResult = http.responseXML;
			if (xmlResult.getElementsByTagName('errorCount')[0].firstChild==null) errorCount = 0;
			else errorCount = xmlResult.getElementsByTagName('errorCount')[0].firstChild.nodeValue;
			if (errorCount==0) {
				var variants = xmlResult.getElementsByTagName('result');
				if (variants.length==1) {
					variant['No'] = variants[0].getElementsByTagName('No')[0].firstChild.nodeValue;
					variant['variant'] = variants.getElementsByTagName('variant')[0].firstChild.nodeValue;
					variant['items'] = variants.getElementsByTagName('items')[0].firstChild.nodeValue;
				} else {
//					var dialog = document.getElementById('vendor_dialog');
//					filltable(vendor);
//					dialog.showModal();
					URI = '/variant/variantdialog/No/'+row.getElementById('v_no_'+line).value;
					result=window.showModalDialog(URI,null,
		                       'dialogWidth=600px;dialogHeight=400px;diologLeft=0;dialogTop=100;resizable=yes;scroll=yes');
					document.getElementById('vendor_no').value = result['no'];
					document.getElementById('vendor_name').innerHTML = result['name'];
				}
			} else {
				var errors = xmlResult.getElementsByTagName('error');
				for (e = 0; e < errorCount; e++) {
					field = errors[e].childNodes[1].nodeName;
					value = errors[e].childNodes[1].firstChild.nodeValue;
					var errorText = errorText+"["+field+"] "+value+"\n";d
				}
				alert(errorText);
			}
		}
	}

}
</script>


<?php //Zend_Debug::dump($this->params); ?>
<?php $data = $this->params['data']; ?>
<?php $errors = $this->params['errors']; ?>
<form action="/inbound/edit/" method="post">
<legend><?php echo $this->params['title']; ?></legend>
<fieldset>
<?php if (isset($this->errors['all'])) : ?><div class="error">
<?php echo $this->errors['all']; ?>
</div><?php  endif ?>
<table>
	<tr><td><div id="vendor_address"></div></tr>
	<tr>
		<td></td><td><input type="hidden" name="old_No" value="<?php echo $data['No']; ?>" /></td>
	</tr>
	<tr>
		<td>Position</td>
		<td>
			<?php if (isset($errors['No'])) :?><div class="error"><?php endif ?>
			<input type="text" name="No" value="<?php echo $data['No']; ?>" />
			<?php if (isset($errors['No'])) :?><br /><?php echo $errors['No']; ?></div><?php endif ?>
		</td>
		<td>Lieferant</td>
		<td>
			<?php if (isset($errors['vendor'])) :?><div class="error"><?php endif ?>
			<input type="text"  id="vendor" name="vendor" value="<?php echo $data['vendor']; ?>" onchange="loadVendor()"/>
			<?php if (isset($errors['vendor'])) :?><br /><?php echo $error['vendor']; ?></div><?php endif ?>
		</td>
	</tr>
	<tr>
		<td>Bestellung</td>		
		<td><input type="text" id="purchase_order" name="purchase_order" size="20" maxlength="20" value="<?php echo $data['vendor']; ?>" onchange="loadPO()" />
		<td>Spedition</td>
		<td><input type="text" name="spedition" size="30" maxlength="100" /></td>
	</tr>
	<tr>
		<td>Container / AWB</td>
		<td><input type="text" name="container" maxlength="40" size="40" value="<?php echo $data['container']; ?>" /></td>
		<td>Fahrzeug</td>
		<td><input type="text" name="trailor" maxlength="40" size="40" value="<?php echo $data['trailor']; ?>" /></td>
	</tr>
	<tr>
		<td>Ankunft geplant</td>
		<td>
			<input type="text" name="po_arrival_date" maxlength="10" size="10" value="<?php echo $data['arrival_date']; ?>" /> <input type="text" name="po_arrival_time" size="8" maxlength="8" value=<?php echo $data['arrival_time']; ?>" />
		</td>
		<td>
			<table>
			<tr><td>Temp. Soll</td><td>Temp. Ist</td></tr>
			<tr>
				<td><input type="text" name="transport_temp_qequired" value="<?php echo $data['transport_temp_required']; ?>" /></td>
			    <td><input type="text" name="transport_temp_current" value="<?php echo $data['transport_temp_current']; ?>" /></td>
			</tr>
			</table>
	</tr>
	<tr>
		<td>Ankunftszeit</td>
		<td>
			<input type="text" name="ib_arrival_date" maxlength="10" size="10" value="<?php echo $data['arrival_date']; ?>" /> <input type="text" name="po_arrival_time" size="8" maxlength="8" value=<?php echo $data['arrival_time'];?>" />
		</td>
	</tr>
	</tr>
		<td></td><td><input type="submit" name="submit" value="Speichern" /> <input type="submit" name="submit" value="Abbrechen" /></td>
	</tr>
</table>
<hr />
<button type="button" value="neue Variante" onclick="newVariant()" />
<table id="inbound_lines">
<thead>
	<th class="data" width="20">Variante</th>
	<th class="data" width="150">Beschreibung</th>
	<th class="data" width="10">Kolli</>
	<th class="data" width="10">Menge/Kolli</th>
	<th class="data" width="12">Menge ges.</th>
	<th class="data" width="10">Kolli geliefert</th>
	<th class="data" width="6">Paletten</th>
	<th class="data" width="10">Kolli / Pal.</th>
</thead>
<tbody>
<?php (foreach $inbLines as $line) : ?>
<tr>
	<td class="data"><?php echo $line['v_no']; ?></td>
	<td class="data"><?php echo $line['variant']; ?></td>
	<td class="data"><?php echo $line['trading_units']; ?></td>
	<td class="data"><?php echo $line['PU_TU']; ?></td>
	<td class="data"><?php echo $line['packing_units']; ?></td>
	<td class="data"><input type="number" name="inbound_TUs" value="<?php echo $line['inbound_TUs']; ?>" size="10" maxlength="10" /></td>
	<td class="data"><input type="number" name="inbound_pallets" value="<?php $line['inbound_pallets']; ?>" size="6" maxlength="6" /></td>
	<td class="data"><input type="number" name="inbound_TU_Pal" value="<?php $line['inbound_TU_Pal']; ?>" size="5" maxlength="5" /></td>
</tr>
</tbody>
</table>
</form>

<dialog id="vendor_dialog">
<h2>Lieferant ausw‰hlen"</h2>
<form method="get">
<table id="vendor_table">
<thead>
<tr>
	<th class="data">Kred-Nr.</th>
	<th class="data">Kreditor</th>
	<th class="data">Straﬂe</th>
	<th class="data">Ort</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<button type="submit" value="Ausw‰hlen">
</form>
</dialog>