<script>
function createRow(row, localization)
{
	row.id = localization.No;
	cell0 = row.insertCell(0);
	if (localization.No!='new') {
		cell0.innerHTML = '<a onclick="deleteLabel(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a>';
	}
	cell1 = row.insertCell(1);
	cell1.className = 'data';
	selectLang = document.getElementById('ini_language').cloneNode(true);
	selectLang.style = 'width: 99%';
	selectLang.id = row.id+'_language';
	selectLang.name = row.id+'_language';
	selectLang.value = localization.language;
	cell1.appendChild(selectLang);
	cell2 = row.insertCell(2);
	cell2.className = 'data'
	inpLabel = document.createElement('input');
	inpLabel.style = 'width: 99%';
	inpLabel.maxlength = 255;
	inpLabel.name = row.id+'_label';
	inpLabel.id = row.id+'_label';
	inpLabel.value = localization.entry;
	inpLabel.onchange = function() { updateLanguage(this); };
	cell2.appendChild(inpLabel);
	cell3 = row.insertCell(3);
	cell3.className = 'data'
	inpLabelShort = document.createElement('input');
	inpLabelShort.style = 'width: 99%';
	inpLabelShort.maxlength = 5;
	inpLabelShort.name = row.id+'_label_short';
	inpLabelShort.id = row.id+'_label_short';
	inpLabelShort.value = localization.entry;
	inpLabelShort.onchange = function() { updateLanguage(this); };
	cell3.appendChild(inpLabelShort);
}

function createNewRow(row)
{
	var localization = new Object();
	localization.No = 'new';
	localization.language = '';
	localization.entry = '';
	createRow(row, localization);
}

function updateLanguage(element)
{
	function updateLangXML()
	{
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {					
					language.value = getXMLTagValue(http.responseXML, 'language') || '';
					label.value = getXMLTagValue(http.responseXML, 'label') || '';
					labelShort.value = getXMLTagValue(http.responseXML, 'label_short') || '';
					if (row.id != getXMLTagValue(http.responseXML, 'No')) {
						row.id =  getXMLTagValue(http.responseXML, 'No');
						row.cells[0].innerHTML = '<a onclick="deleteLanguage(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a>';
						language.id = row.id+'_language';
						language.name = row.id+'_language';
						label.id = row.id+'_label';
						label.name = row.id+'_label';
						labelShort.name = row.id+'_label_short';
						labelShort.id = row.id+'_label_short';
						languageTable = document.getElementById('languages').getElementsByTagName('tbody')[0];
						createNewRow(languageTable.insertRow(languageTable.rows.length));
					}
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	
	send = true;
	var row = element.parentNode.parentNode;
	var No = row.id;
	var type = document.getElementById('type');
	var table = document.getElementById('table');
	var column = document.getElementById('column');
	var language = document.getElementById(No+'_language');
	var label = document.getElementById(No+'_label');
	var labelShort = document.getElementById(No+'_label_short');
	var params = 'No='+No+'&type='+type.value+'&language='+language.value+'&table_name='+table.value+'&column_name='+column.value+'&label='+label.value+'&label_short='+labelShort.value;
	if (No=='new') send = confirm('Ein neuer Eintrag wird angelegt!');
	uri = '/language/editlabel';
	if (send) {
		createRequest();
		sendRequest('POST', uri, params, updateLangXML, false);
	}
}

function deleteLanguage(element)
{
	function deleteLangXML()
	{
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {
					languageTable = document.getElementById('languages').getElementsByTagName('tbody')[0];
					languageTable.deleteRow(row.sectionRowIndex);
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	
	var row = element.parentNode.parentNode;
	var No = row.id;
	var table = document.getElementById('table');
	var column = document.getElementById('column');
	var language = document.getElementById(No+'_language');
	params = 'delete=DELETE&No='+No+'&language='+language.value+'&table_name='+table.value+'&column_name='+column.value;
	uri = '/language/deletelabel/';
	if (confirm('Der Eintrag wird gelöscht!')) {
		createRequest();
		sendRequest('POST', uri, params, deleteLangXML, false);
	}
}

</script>
<?php // Zend_Debug::dump($this->params); ?>
<div class="data_container">
<input type="hidden" id="type" name="type" value="<?php echo $this->params['type']; ?>" />
<input type="hidden" id="table" name="table" value="<?php echo $this->params['view']; ?>" />
<input type="hidden" id="column" name="column" value="<?php echo $this->params['column']; ?>" />
<?php echo $this->lookupSelect('ini_language', '', 'language', $this->params['languages'], 'Id', 'language', array('id'=>'ini_language', 'onchange'=>'updateLanguage(this)')); ?>
</div>
<?php if (count($this->params['errors'])>0) : ?>
<div class="error">
<?php foreach ($this->params['errors'] as $key => $error) echo "$key: $error<br 7>"; ?>
</div>
<?php endif ?>
<div>Übersetzung für: <b><?php echo $this->params['column']; ?></b></div>
<table id="languages">
<thead>
<tr>
	<th width="20px"></th>
	<th class="data" width="100px">Land</th>
	<th class="data">Label</th>
	<th class="data">Label kurz</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->data as $localization) : ?>
<tr id="<?php echo $localization['No']; ?>">
<td><a onclick="deleteLanguage(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a></td>
<td class="data"><?php echo $this->lookupSelect($localization['No'].'_language', $localization['language'], 'language', $this->params['languages'], 'Id', 'language', array('id'=>$localization['No'].'_language', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%')); ?></td>
<td class="data"><?php echo $this->formText($localization['No'].'_label', $localization['label'], array('id'=>$localization['No'].'_label', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'255')); ?></td>
<td class="data"><?php echo $this->formText($localization['No'].'_label_short', $localization['label_short'], array('id'=>$localization['No'].'_label_short', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'5')); ?></td>
</tr>
<?php endforeach ?>
<tr id="new">
<td></td>
<td class="data"><?php echo $this->lookupSelect('new_language', '', 'language', $this->params['languages'], 'Id', 'language', array('id'=>'new_language', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%')); ?></td>
<td class="data"><?php echo $this->formText('new_label', '', array('id'=>'new_label', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'255')); ?></td>
<td class="data"><?php echo $this->formText('new_label_short', '', array('id'=>'new_label_short', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'5')); ?></td>
</tr>
</tbody>
</table>