<script>
function createRow(row, localization)
{
	row.id = localization.No;
	cell0 = row.insertCell(0);
	if (localization.No!='new') {
		cell0.innerHTML = '<a onclick="deleteLanguage(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a>';
	}
	cell1 = row.insertCell(1);
	cell1.className = 'data';
	selectLang = document.getElementById('ini_language').cloneNode(true);
	selectLang.style = 'width: 99%';
	selectLang.id = row.id+'_language';
	selectLang.name = row.id+'_language';
	selectLang.value = localization.language;
	cell1.appendChild(selectLang);
	cell2 = row.insertCell(2);
	cell2.className = 'data'
	inpEntry = document.createElement('input');
	inpEntry.style = 'width: 99%';
	inpEntry.name = row.id+'_entry';
	inpEntry.id = row.id+'_entry';
	inpEntry.value = localization.entry;
	cell2.appendChild(inpEntry);
}

function createNewRow(row)
{
	var localization = new Object();
	localization.No = 'new';
	localization.language = '';
	localization.entry = '';
	createRow(row, localization);
}

function updateLanguage(element)
{
	function updateLangXML()
	{
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {					
					language.value = getXMLTagValue(http.responseXML, 'language') || '';
					entry.value = getXMLTagValue(http.responseXML, 'entry') || '';
					if (row.id != getXMLTagValue(http.responseXML, 'No')) {
						row.id =  getXMLTagValue(http.responseXML, 'No');
						row.cells[0].innerHTML = '<a onclick="deleteLanguage(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a>';
						language.id = row.id+'_language';
						language.name = row.id+'_language';
						entry.id = row.id+'_entry';
						entry.name = row.id+'_entry';
						languageTable = document.getElementById('languages').getElementsByTagName('tbody')[0];
						createNewRow(languageTable.insertRow(languageTable.rows.length));
					}
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	
	send = true;
	var row = element.parentNode.parentNode;
	var No = row.id;
	var table = document.getElementById('table');
	var column = document.getElementById('column');
	var key = document.getElementById('key');
	var language = document.getElementById(No+'_language');
	var entry = document.getElementById(No+'_entry');
	var params = 'No='+No+'&language='+language.value+'&table_name='+table.value+'&column_name='+column.value+'&key_val='+key.value+'&entry='+entry.value;
	if (No=='new') send = confirm('Ein neuer Eintrag wird angelegt!');
	uri = '/language/edit';
	if (send) {
		createRequest();
		sendRequest('POST', uri, params, updateLangXML, false);
	}
}

function deleteLanguage(element)
{
	function deleteLangXML()
	{
		if (http.readyState == 4) {
			if (http.responseXML) {
				errorCount = getXMLTagValue(http.responseXML, 'errorCount') || 0;
				if (errorCount==0) {
					languageTable = document.getElementById('languages').getElementsByTagName('tbody')[0];
					languageTable.deleteRow(row.sectionRowIndex);
				} else {
					var errTxt = '';
					errors = http.responseXML.getElementsByTagName('error');
					for (ec = 0; ec<errors.length; ec++) {
						errTxt+=getXMLTagValue(errors[ec], 'error_field')+' ';
						errTxt+=getXMLTagValue(errors[ec], 'error_text')+'\n';
					}
					alert(errTxt);
				}
			} else {
				alert(http.responseText);
			}
		}
	}
	
	var row = element.parentNode.parentNode;
	var No = row.id;
	var table = document.getElementById('table');
	var column = document.getElementById('column');
	var key = document.getElementById('key');
	var language = document.getElementById(No+'_language');
	params = 'delete=DELETE&No='+No+'&language='+language.value+'&table_name='+table.value+'&column_name='+column.value+'&key_val='+key.value;
	uri = '/language/delete/';
	if (confirm('Der Eintrag wird gelöscht!')) {
		createRequest();
		sendRequest('POST', uri, params, deleteLangXML, false);
	}
}

</script>
<?php // Zend_Debug::dump($this->params); ?>
<div class="data_container">
<input type="hidden" id="table" name="table" value="<?php echo $this->params['table']; ?>" />
<input type="hidden" id="column" name="column" value="<?php echo $this->params['column']; ?>" />
<input type="hidden" id="key" name="key" value="<?php echo $this->params['key']; ?>" />
<?php echo $this->lookupSelect('ini_language', '', 'language', $this->params['countries'], 'Id', 'Id', array('id'=>'ini_language', 'onchange'=>'updateLanguage(this)')); ?>
</div>
<div>Übersetzung für: <b><?php echo $this->params['value']; ?></b></div>
<table id="languages">
<thead>
<tr>
	<th width="20px"></th>
	<th class="data" width="100px">Land</th>
	<th class="data">Eintrag</th>
</tr>
</thead>
<tbody>
<?php foreach ($this->data as $localization) : ?>
<tr id="<?php echo $localization['No']; ?>">
<td><a onclick="deleteLanguage(this)"><img src="/images/b_drop.png" alt="löschen" title="löschen" /></a></td>
<td class="data"><?php echo $this->lookupSelect($localization['No'].'_language', $localization['language'], 'language', $this->params['countries'], 'Id', 'Id', array('id'=>$localization['No'].'_language', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%')); ?></td>
<td class="data"><?php echo $this->formText($localization['No'].'_entry', $localization['entry'], array('id'=>$localization['No'].'_entry', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'255')); ?></td>
</tr>
<?php endforeach ?>
<tr id="new">
<td></td>
<td class="data"><?php echo $this->lookupSelect('new_language', '', 'language', $this->params['countries'], 'Id', 'Id', array('id'=>'new_language', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%')); ?></td>
<td class="data"><?php echo $this->formText('new_entry', '', array('id'=>'new_entry', 'onchange'=>'updateLanguage(this)', 'style'=>'width: 99%', 'maxlength'=>'255')); ?></td>
</tr>
</tbody>
</table>